#!/usr/bin/env python
#This program shows how to handle user input from the command line
#raw_input which reads 1 line from standard input and returns it as a string (removing the trailing newline)
str = raw_input("Enter your input: ");
print "Received input is : ", str

#input is equivalent to raw_input, except that it assumes the input is a valid Python expression and returns the evaluated result to you.
str2 = input("Enter your input: ");
print "Received input is : ", str2
